"""Unit tests for shared/errors.py — AgentError hierarchy + FastAPI handler."""
from __future__ import annotations

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from src.shared.errors import (
    AgentError,
    AllocationInsufficient,
    AuthInvalidApiKey,
    AuthMissingApiKey,
    ChainNotSupportedInV1,
    ConfirmationRequired,
    EvaluationError,
    InternalError,
    SchedulerError,
    SdkError,
    SigningError,
    StrategyInvalidComposition,
    StrategyInvalidStatusTransition,
    StrategyNoViableCandidates,
    StrategyNotFound,
    ValidationError,
    WalletAlreadyExists,
    WalletNotFound,
    agent_error_handler,
)


# (class, expected code, expected http status)
ERROR_CASES = [
    (AuthMissingApiKey, "AUTH_MISSING_API_KEY", 401),
    (AuthInvalidApiKey, "AUTH_INVALID_API_KEY", 401),
    (ValidationError, "VALIDATION_ERROR", 400),
    (ConfirmationRequired, "CONFIRMATION_REQUIRED", 400),
    (WalletNotFound, "WALLET_NOT_FOUND", 404),
    (WalletAlreadyExists, "WALLET_ALREADY_EXISTS", 409),
    (StrategyNotFound, "STRATEGY_NOT_FOUND", 404),
    (StrategyInvalidStatusTransition, "STRATEGY_INVALID_STATUS_TRANSITION", 400),
    (StrategyInvalidComposition, "STRATEGY_INVALID_COMPOSITION", 400),
    (StrategyNoViableCandidates, "STRATEGY_NO_VIABLE_CANDIDATES", 422),
    (AllocationInsufficient, "ALLOCATION_INSUFFICIENT", 400),
    (SdkError, "SDK_ERROR", 502),
    (SigningError, "SIGNING_ERROR", 500),
    (EvaluationError, "EVALUATION_ERROR", 500),
    (SchedulerError, "SCHEDULER_ERROR", 500),
    (ChainNotSupportedInV1, "CHAIN_NOT_SUPPORTED_IN_V1", 501),
    (InternalError, "INTERNAL_ERROR", 500),
]


@pytest.mark.parametrize("cls,code,http", ERROR_CASES)
def test_error_class_attributes(cls, code, http):
    """Each subclass carries the spec-defined code and http_status."""
    assert cls.code == code
    assert cls.http_status == http
    assert issubclass(cls, AgentError)


@pytest.mark.parametrize("cls,code,http", ERROR_CASES)
def test_error_to_dict_shape(cls, code, http):
    """to_dict returns the standard response shape."""
    err = cls("something happened", suggestion="try X")
    d = err.to_dict()
    assert d["error"] is True
    assert d["code"] == code
    assert d["message"] == "something happened"
    assert d["suggestion"] == "try X"
    assert "correlation_id" in d
    assert len(d["correlation_id"]) > 0


def test_correlation_id_autogenerated():
    """Unique correlation_id per instance if not passed."""
    a = WalletNotFound("a")
    b = WalletNotFound("b")
    assert a.correlation_id != b.correlation_id


def test_correlation_id_passthrough():
    """Explicit correlation_id is preserved."""
    err = WalletNotFound("a", correlation_id="fixed-id-123")
    assert err.correlation_id == "fixed-id-123"


def test_suggestion_optional():
    """Suggestion is optional and serializes as None when absent."""
    err = WalletNotFound("no suggestion here")
    assert err.suggestion is None
    assert err.to_dict()["suggestion"] is None


def test_handler_returns_error_response_body():
    """FastAPI handler produces the spec-shaped JSON with the right status."""
    app = FastAPI()
    app.add_exception_handler(AgentError, agent_error_handler)

    @app.get("/raise-wallet")
    async def raise_wallet():
        raise WalletNotFound("0xabc", suggestion="check spelling")

    @app.get("/raise-sdk")
    async def raise_sdk():
        raise SdkError("upstream 503")

    client = TestClient(app, raise_server_exceptions=False)

    r = client.get("/raise-wallet")
    assert r.status_code == 404
    body = r.json()
    assert body["error"] is True
    assert body["code"] == "WALLET_NOT_FOUND"
    assert body["message"] == "0xabc"
    assert body["suggestion"] == "check spelling"
    assert "correlation_id" in body

    r = client.get("/raise-sdk")
    assert r.status_code == 502
    assert r.json()["code"] == "SDK_ERROR"
