project_id   = "YOUR_GCP_PROJECT"
region       = "us-central1"
environment  = "dev"
service_name = "YOUR_SERVICE_NAME-dev"
repo_name    = "YOUR_SERVICE_NAME-repo"
image        = "us-central1-docker.pkg.dev/YOUR_GCP_PROJECT/YOUR_SERVICE_NAME-repo/YOUR_SERVICE_NAME:latest"
